version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/chibimi/golang-monorepo/
    docker:
    - image: golang:1.16.3
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.06.0-ce
    - run:
        name: Build monorepo
        shell: /bin/bash
        environment: 
          COMMIT_RANGE: <<pipeline.git.base_revision>>..<<pipeline.git.revision>>
        command: |
          chmod +x ./build.sh
          ./build.sh
